//
// Quality Trimming & Filtering, Adaptor Trimming, and Host Removal
//
include { FASTP                                      } from '../../../modules/nf-core/fastp/main'
include { PARSE_FASTP_REPORTS                        } from '../../../modules/local/preprocess/parse_fastp/main'
include { COMBINE_FASTP_REPORTS                      } from '../../../modules/local/preprocess/combine_reports/main'
include { SEQTK_MERGEPE                              } from '../../../modules/nf-core/seqtk/mergepe/main'
include { SRA_HUMAN_SCRUBBER                         } from '../../../modules/local/sra-human-scrubber/main'
include { SEQFU_DEINTERLEAVE                         } from '../../../modules/local/seqfu/deinterleave/main'
include { SEQKIT_SAMPLE                              } from '../../../modules/local/seqkit/sample/main'

include { ALIGNMENT                                  } from '../alignment/main'
include { ALIGNMENT as ALIGN_DOWNSAMPLED             } from '../alignment/main'

workflow PREPROCESSING {
    take:
    reads          // channel: [ id: meta, [ reads ] ]
    ch_faidx       // channel: [ meta, index ]

    main:

    ch_versions = Channel.empty()

    ch_reads = reads
                    .map {
                        meta, reads ->
                            [ meta, reads, []]
                    }

    ch_fastq = Channel.empty()
    //
    // MODULE: Quality trimming & filtering and adaptor trimming with fastp
    //
    FASTP (
        ch_reads,
        false,
        false,
        false
    )
    ch_fastq = FASTP.out.reads
    ch_versions = ch_versions.mix(FASTP.out.versions)

    //
    // MODULE: Parse JSON report generated by fastp & report relevant FASTQ quality metrics 
    //
    ch_fastp_report = Channel.empty()
    PARSE_FASTP_REPORTS (
        FASTP.out.json
    )
    ch_fastp_report = PARSE_FASTP_REPORTS.out.tsv_path
    ch_versions = ch_versions.mix(PARSE_FASTP_REPORTS.out.versions)

    //
    // MODULE: Combine reports for all samples into one report
    //
    COMBINE_FASTP_REPORTS (
        ch_fastp_report.collect()
    )
    ch_versions = ch_versions.mix(COMBINE_FASTP_REPORTS.out.versions)

    if (params.host_removal){
        //
        // MODULE: Use sra-human-scrubber
        //
        SEQTK_MERGEPE (
            ch_fastq
        )
        ch_versions = ch_versions.mix(SEQTK_MERGEPE.out.versions)

        SRA_HUMAN_SCRUBBER (
            SEQTK_MERGEPE.out.reads,
            "${params.human_db}"
        )
        ch_versions = ch_versions.mix(SRA_HUMAN_SCRUBBER.out.versions)

        SEQFU_DEINTERLEAVE (
            SRA_HUMAN_SCRUBBER.out.reads
        )
        ch_versions = ch_versions.mix(SEQFU_DEINTERLEAVE.out.versions)
        ch_fastq = SEQFU_DEINTERLEAVE.out.reads
    }

    //
    // SUBWORKFLOW: Perform alignment to Mp reference with Minimap2 and report stats
    //
    ALIGNMENT (
        ch_fastq,
        "cov_depth.tsv",
        ch_faidx
    )
    ch_versions = ch_versions.mix(ALIGNMENT.out.versions)

    ch_stats = ALIGNMENT.out.ch_stats
    ch_bam_bai = ALIGNMENT.out.bam_bai
    ch_merge = ALIGNMENT.out.stats


    ch_ds = Channel.empty()
    
    if (params.downsample){ 

        //Get normalized average depth of coverage and divide depth to sample to by that to get proportion to give to SEQKIT sample
        ch_depth = ch_stats
                    .map {
                        meta, stats ->
                        def file = stats
                                    .splitCsv(skip:1,sep:"\t").first()
                        def float norm = "${file[3]}" as float
                        def int depth = "${params.depth}" as int
                        def prop = depth / norm
                        return [ meta, prop ]
                    }
                    .branch {
                        meta, proportion ->
                        downsample: proportion < 1
                        skip: proportion > 1
                    }

        ch_sample = ch_depth.downsample.join(ch_fastq)
                        .map {
                            meta, prop, reads ->
                            [ meta, reads, prop]
                        }

        ch_skip = ch_depth.skip.join(ch_fastq)
                        .map {
                            meta, proportion, reads ->
                            [ meta, reads ]
                        }

        //
        // MODULE: Downsample reads by proportion
        //
        SEQKIT_SAMPLE (
            ch_sample
        )
        ch_versions = ch_versions.mix(SEQKIT_SAMPLE.out.versions)
        ch_fastq = SEQKIT_SAMPLE.out.downsampled.mix(ch_skip)

        //
        // MODULE: Align downsampled reads to the reference
        //
        ALIGN_DOWNSAMPLED (
            SEQKIT_SAMPLE.out.downsampled,
            "downsampled_cov_depth.tsv",
            ch_faidx
        )
        ch_versions = ch_versions.mix(ALIGN_DOWNSAMPLED.out.versions)

        // ch_bam_bai = ch_depth.skip.join(ch_bam_bai)
        //                 .map{
        //                     meta, prop, bam, bai ->
        //                     [ meta, bam, bai ]
        //                 }.mix(ALIGN_DOWNSAMPLED.out.bam_bai)
        ch_ds = ALIGN_DOWNSAMPLED.out.stats
    }


    emit:

    fastp_report        = COMBINE_FASTP_REPORTS.out.fastp_report        // channel:  fastp_report 
    json                = FASTP.out.json                                // channel:  [ id: meta, json ]

    stats               = ch_merge                                      // channel: [ cov_depth.tsv ]

    ds_stats            = ch_ds                                         // channel: [ downsampled_cov_depth.tsv ]

    reads               = ch_fastq                                      // channel: [ id: meta, [ reads ] ]

    bam_bai             = ch_bam_bai                                    // channel: [ meta, bam, bai ]


    versions            = ch_versions                                   // channel: [ versions.yml ]

}